---
title: "GWAS catalog"
output:
  html_document: default
  pdf_document: default
---

```{r setup}
library(pander)
library(dplyr)
library(reshape2)
library(ggplot2)
```

# About loaded data.frame

The script to generate the input data.frame can be found [here](https://bitbucket.org/yanyul/rotation-at-imlab/src/master/analysis/annotate_gwas_catalog/summary/output/gen_table_sub_new.R)

The full script is shown below

```
library(data.table)
options(datatable.fread.datatable = F)
library(dplyr)
df = readRDS('tables.rds')
df_gwas_gtex_table = df$df_gwas_gtex_table
df_gwas_table = df$df_gwas_table
summary_gwas_variant <- data.frame(gwas_table_idx = 1 : nrow(df_gwas_table), gwas_id = df_gwas_table$rsID)
summary_gwas_variant$gtex_id <- rep(NA, nrow(df_gwas_table))
summary_gwas_variant$gtex_id[match(df_gwas_gtex_table$rsID, df_gwas_table$rsID)] <- df_gwas_gtex_table$GTExID


list_signif_eqtl = fread('../../output/ALL.signif_eqtl.GTExFDRlt0.05.txt', header = F)
list_signif_sqtl = fread('../../output/ALL.signif_eqtl.GTExSQTLFDRlt0.05.txt', header = F)

list_tested_eqtl = fread('../../output/ALL.tested_eqtl.GTExV8TestedEQTL.txt', header = F)
list_tested_sqtl = fread('../../output/ALL.tested_eqtl.GTExV8TestedSQTL.txt', header = F)

list_tested_trans_eqtl = fread('../../output/ALL.tested_trans_eqtl.GTExTestedTransEQTL.txt', header = F) 
list_signif_trans_eqtl1 = fread('/gpfs/data/gtex-group/v8/trans-eQTL/trans_egenes/trans_genes_lincRNA_FDR_0.1.tsv') 
list_signif_trans_eqtl2 = fread('/gpfs/data/gtex-group/v8/trans-eQTL/trans_egenes/trans_genes_protein_coding_FDR_0.1.tsv') 
list_signif_trans_eqtl = union(list_signif_trans_eqtl1$rsid, list_signif_trans_eqtl2$rsid)

my_summarize = function(gwas_table, tested_list, signif_list) {
  # table
  # type  tested  signif
  # gwas  t_gwas  s_gwas
  # all   t_all   s_all
  t_all = length(tested_list)
  s_all = length(signif_list)
  gwas = gwas_table %>% filter(!is.na(gtex_id)) %>% filter(!duplicated(gwas_id)) %>% mutate(is_tested = gtex_id %in% tested_list, is_signif = gtex_id %in% signif_list)
  t_gwas = sum(gwas$is_tested)
  s_gwas = sum(gwas$is_signif)
  data.frame(type = c('gwas', 'all'), tested = c(t_gwas, t_all), signif = c(s_gwas, s_all))
}
list_tested_eqtl = list_tested_eqtl$V1
list_signif_eqtl = list_signif_eqtl$V1
list_tested_sqtl = list_tested_sqtl$V1
list_signif_sqtl = list_signif_sqtl$V1
list_tested_trans_eqtl = list_tested_trans_eqtl$V1
eqtl = my_summarize(summary_gwas_variant, list_tested_eqtl, list_signif_eqtl)
sqtl = my_summarize(summary_gwas_variant, list_tested_sqtl, list_signif_sqtl)
trans_eqtl = my_summarize(summary_gwas_variant, list_tested_trans_eqtl, list_signif_trans_eqtl)
ngwas = sum(!duplicated(summary_gwas_variant$gwas_id))


saveRDS(list(eqtl = eqtl, sqtl = sqtl, trans_eqtl = trans_eqtl, ngwas = ngwas), 'table_sub_new.rds')
```



# Load data.frame

```{r paths}
df = readRDS('data/gwas_catalog_tables.rds')
eqtl = df$eqtl
sqtl = df$sqtl
trans_eqtl = df$trans_eqtl
ngwas = df$ngwas
```

# Count table

```{r}
eqtl %>% pander(caption = 'cis-eQTL')
sqtl %>% pander(caption = 'cis-sQTL')
trans_eqtl %>% pander(caption = 'trans-eQTL')
```

# QTL rate: GWAS catalog vs. overall

```{r}
rate = eqtl %>% mutate(rate = signif / tested, qtl = 'eqtl') 
rate = rbind(rate, sqtl %>% mutate(rate = signif / tested, qtl = 'sqtl'))
rate = rbind(rate, trans_eqtl %>% mutate(rate = signif / tested, qtl = 'trans_eqtl'))
rate %>% ggplot() + geom_bar(aes(x = type, y = rate, fill = type), stat = 'identity') + facet_wrap(~qtl, scales = 'free_y') + ggtitle('Significant QTL rate')
```

# Test rate (percentage of GWAS catalog variants are tested for QTL)

```{r}
rate = eqtl %>% filter(type == 'gwas') %>% mutate(rate = tested / ngwas, qtl = 'eqtl')
rate = rbind(rate, sqtl %>% filter(type == 'gwas') %>% mutate(rate = tested / ngwas, qtl = 'sqtl'))
rate = rbind(rate, trans_eqtl %>% filter(type == 'gwas') %>% mutate(rate = tested / ngwas, qtl = 'trans_eqtl'))
rate %>% ggplot() + geom_bar(aes(x = qtl, y = rate), stat = 'identity') + ggtitle('Percentage of GWAS catalog variants are tested for QTL')
```

